language: java
jdk:
 - openjdk11

script:
- mvn clean verify -Dlicense.skipDownloadLicenses=true

notifications:
 email:
   recipients:
    - travis-ci.mellifluent@hohenegger.eu
   on_success: change
   on_failure: always
