name: Dependabot PR Auto-Merge

on:
  pull_request:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode verify

  automerge:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          target: patch
          exclude: 'spoon-core'
          github-token: ${{ secrets.GITHUB_TOKEN }}